version: '3'
services:
  app:
    build:
     context: ./
     dockerfile: Dockerfile
    container_name: seats-frontend
    image: seats-frontend:latest
    volumes:
      - ./:/app
    environment:
      PORT: 3000
    ports:
      - 3000:3000
